AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Simple S3 bucket

Resources:

  mys3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sean.storage.bucket
      Tags:
        - Key: value
          Value: trash
